export const CHECK_REQUEST = 'REQUEST_CHECK_INPUT_DATA'
export const CHECK_FAIL = 'FAIL_CHECK_INPUT_DATA'
export const CHECK_SUCCESS = 'SUCCESS_CHECK_INPUT_DATA'

export const SUBMIT_REQUEST = 'REQUEST_SUBMIT_INPUT_DATA'
export const SUBMIT_FAIL = 'FAIL_SUBMIT_INPUT_DATA'
export const SUBMIT_SUCCESS = 'SUCCESS_SUBMIT_INPUT_DATA'
